---
- name: gather operating system variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution_file_variety | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
    - "{{ ansible_os_family | lower }}.yml"

- name: create system group
  group:
    name: "{{ telegram_system_group }}"
    system: true
    state: present
  when: telegram_system_group != "root"
  become: true
  tags: telegram

- name: create system user
  user:
    name: "{{ telegram_system_user }}"
    system: true
    shell: "/sbin/nologin"
    group: "{{ telegram_system_group }}"
    createhome: false
  when: telegram_system_user != "root"
  become: true
  tags: telegram

- name: create configuration and data directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ telegram_system_user }}"
    group: "{{ telegram_system_group }}"
    mode: 0755
  with_items:
    - "{{ telegram_config_dir }}"
    - "{{ telegram_template_dir }}"
  become: true
  tags: telegram

- name: check if telegram is installed
  stat:
    path: "{{ telegram_binary_install_dir }}/telegram"
  register: __telegram_is_installed
  become: true
  tags: telegram

- name: download binary to bin folder
  get_url:
    url: "https://github.com/metalmatze/alertmanager-bot/releases/download/{{ telegram_version }}/alertmanager-bot-{{ telegram_version }}-linux-{{ go_arch }}"
    dest: "/tmp/telegram-{{ telegram_version }}.linux-{{ go_arch }}"
  environment: "{{ proxy_env }}"
  register: _download_binary
  until: _download_binary is succeeded
  retries: 5
  delay: 2
  delegate_to: localhost
  check_mode: false
  become: true
  tags: telegram
  when: (not __telegram_is_installed.stat.exists)

- name: propagate binaries
  copy:
    src: "/tmp/telegram-{{ telegram_version }}.linux-{{ go_arch }}"
    dest: "{{ telegram_binary_install_dir }}/telegram"
    mode: 0755
    owner: root
    group: root
  notify: restart telegram
  become: true
  tags: telegram
  when: (not __telegram_is_installed.stat.exists)

- name: copy message templates
  copy:
    src: "{{ telegram_config_template }}"
    dest: "{{ telegram_config_dir }}/templates/{{ telegram_config_template }}"
    mode: 0755
    owner: root
    group: root
  notify: restart telegram
  become: true
  tags: telegram

- name: create systemd service unit
  template:
    src: telegram.service.j2
    dest: /etc/systemd/system/telegram.service
    owner: root
    group: root
    mode: 0644
  notify: restart telegram
  become: true
  tags: telegram

- name: enable capabilities to ports lower than port 1024
  capabilities:
    path: "{{ telegram_binary_install_dir }}/telegram"
    capability: CAP_NET_BIND_SERVICE+ep
    state: present
  when: telegram_listen_port <= 1024
  tags: telegram

- name: install selinux dependencies
  package:
    name: "{{ item }}"
    state: present
  environment: "{{ proxy_env }}"
  with_items: "{{ telegram_selinux_packages }}"
  register: _install_packages
  until: _install_packages is succeeded
  retries: 5
  delay: 2
  when:
    - ansible_version.full is version_compare('2.4', '>=')
    - ansible_selinux.status == "enabled"
  become: true
  tags: telegram

- name: allow binding to port in selinux
  seport:
    ports: "{{ telegram_listen_port }}"
    proto: tcp
    setype: http_port_t
    state: present
  when:
    - ansible_version.full is version_compare('2.4', '>=')
    - ansible_selinux.status == "enabled"
  become: true
  tags: telegram

- name: check whether ufw status is active
  command: "ufw status"
  changed_when: False
  ignore_errors: True
  register: _ufw_status
  become: true
  when:
    - telegram_allow_firewall
    - ansible_os_family == 'Debian'
  tags: telegram

- name: check whether firewalld status is active
  command: "firewall-cmd --state"
  changed_when: False
  ignore_errors: True
  register: _firewalld_status
  become: true
  when: ansible_os_family == 'RedHat'
  tags: telegram

- name: configure ufw
  community.general.ufw:
    rule: allow
    port: "{{ telegram_listen_port }}"
    proto: tcp
    state: enabled
    comment: "Alertmanager telegram"
  changed_when: False
  ignore_errors: True
  notify: reload ufw
  become: true
  tags: telegram
  when:
    - "'active' in _ufw_status.stdout"
    - ansible_os_family == 'Debian'
    - telegram_allow_firewall

- name: configure firewalld
  firewalld:
    port: "{{ telegram_listen_port }}/tcp"
    permanent: yes
    state: true
  changed_when: False
  ignore_errors: True
  when:
    - "'running' in _firewalld_status.stdout"
    - telegram_allow_firewall
    - ansible_os_family == 'RedHat'
  notify: reload firewalld
  become: true
  tags: telegram

- name: ensure telegram service is started and enabled
  systemd:
    daemon_reload: true
    name: telegram
    state: restarted
    enabled: true
  become: true
  tags: telegram
